### PR TITLE
Stop sharing when leaving

### LINKED ISSUE #174: BUG: When a user is sharing their screen and leaves the room, the screen is still being shown to other participants even though the user has left the room.
When a user is sharing their screen in a room and then leaves the room, the screen is still being shown to other participants even though the user has left the room. This can cause confusion and disrupt the meeting flow as participants may still think that the user is still present in the room.

Steps to reproduce:

1- Have a user join a room and share their screen.
2- Have the user leave the room.
Observe that the screen is still being shown to other participants.
Expected result:
When a user leaves the room while sharing their screen, the screen should stop being shown to other participants.

### PR DESCRIPTION
**Pull request by fpyoung**
Fixes #174

### CODE REVIEW

File: frontend/src/views/Room.jsx [hunk 1]
```diff
@@ -315,6 +315,12 @@ function Room() {
     setIsSharingScreen(!isSharingScreen);
   };
 
+  useEffect(() => () => {
```
Comment (DuckyCB) [inline frontend/src/views/Room.jsx:318]: does it work without the second `() =>`?

**Review by yulianag-qualabs — APPROVED** [review]

File: frontend/src/views/Room.jsx (hunk 1 above)
Comment (fpyoung) [reply frontend/src/views/Room.jsx:318]: hey Pato! nice catch! I was googling and I found out that this is equivalent to write this:
`  useEffect(() => { return () => { if (isSharingScreen) { updateScreenShare(); } }; }, [isSharingScreen]);`

Turns out when you make a double arrow function on a useEffect that function only will be triggered like a cleanup function.
